### ISSUE TITLE
Writing sld files?

### ISSUE THREAD

**Issue by 1000000000000000000000000000000** [princelab/xcalibur-sld#1]
Hello, I haven't tried this repo yet (looks great though!) but it looks like it can read sld files. I am looking for something to write sld files because the software is a pain to use. I was thinking about making an app to convert excel files to a mass spec run sequence file (.sld) to run the Thermo instrument. At first, I was thinking this could be semi-trivial but I have been surprised by how little progress I've been able to make. Is there a way to write these kinds of files that anyone knows of? Thanks!

**Comment by jtprince** [comment]
I haven't worked with SLD files in quite some time, but my memory is that there's a lot of information in them that's not necessarily understood or being accessed with this reader (I spent a long time decrypting aspects of it, but it was a slog and I don't remember being able to decode it all).  In other words, getting to the point where a person could _write_ one of these files is much more difficult than decoding parts of them in the manner that we have done here.

So, unless some sort of specification is found or released by Thermo, I would argue that this is effectively impossible (or at least, not worth the amount of effort to get there)? [so, while I thank you for the issue, I'm going to close it for now]
